### ISSUE TITLE
"Sorry, this file is invalid so it cannot be displayed." for "deep_cmake_for_library_authors__craig_scott__cppcon_2019.pdf"

### ISSUE THREAD

**Issue by galv** [CppCon/CppCon2019#2]
It seems that the Deep CMake library presentation file is wrong. I'm getting this message "Sorry, this file is invalid so it cannot be displayed." when I try to access its page: https://github.com/CppCon/CppCon2019/blob/master/Presentations/deep_cmake_for_library_authors/deep_cmake_for_library_authors__craig_scott__cppcon_2019.pdf

**Comment by galv** [comment]
FYI @crascit

**Comment by audiofanatic** [comment]
Yes, known issue and already in discussion with the organisers/maintainers. The PDF file is too large for GitHub to display. I'm working on making it available on my website and having a link put here to redirect people to it. Should hopefully get that done in the next week or so.

**Comment by DasNaCl** [comment]
Perhaps `ps2pdf` or ghostscript-hackery helps to reduce the file size enough.

**Comment by jeremyong** [comment]
Maybe just simple zip/tar compression?

**Comment by audiofanatic** [comment]
The PDF has been updated with a much smaller version. I've confirmed you can successfully download it from GitHub now, so I recommend this issue be closed.
