### ISSUE TITLE
Slides missing: "Back to Basics: Move Semantics" by Klaus Iglberger

### ISSUE THREAD

**Issue by turingcompl33t** [CppCon/CppCon2019#7]
The talk I am referring to:
- [Part 1](https://www.youtube.com/watch?v=St0MNEU5b0o)
- [Part 2](https://www.youtube.com/watch?v=pIzaZbKUw2s)

A fantastically engaging and insightful talks; it would be a shame to not publish these slides!

**Comment by JonKalb** [comment]
Klaus's submission to us was blocked by a spam filter, but has just been unblocked.
